name: Deploy Development to Hostinger (Subdomain)

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build (development release)
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL_DEV }}
        run: npm run build

      - name: Ensure .htaccess is present in dist
        run: |
          if [ -f "public/.htaccess" ]; then
            cp -f public/.htaccess dist/.htaccess
          fi

      - name: Debug FTP root and target path
        shell: bash
        run: |
          sudo apt-get update -y >/dev/null 2>&1
          sudo apt-get install -y lftp >/dev/null 2>&1
          TARGET_DIR="${{ endsWith(secrets.FTP_SERVER_DIR_DEV, '/') && secrets.FTP_SERVER_DIR_DEV || format('{0}/', secrets.FTP_SERVER_DIR_DEV) }}"
          echo "Listing FTP root and target directory (values masked in logs)"
          lftp -e "set ftp:ssl-force true; set ssl:verify-certificate false; set ftp:passive-mode true; pwd; cls -l; cd $TARGET_DIR; pwd; cls -l; bye" -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" "ftps://${{ secrets.FTP_SERVER }}:21"

      - name: Deploy via FTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ${{ endsWith(secrets.FTP_SERVER_DIR_DEV, '/') && secrets.FTP_SERVER_DIR_DEV || format('{0}/', secrets.FTP_SERVER_DIR_DEV) }}
          protocol: ftps
          dangerous-clean-slate: true
          log-level: verbose
          timeout: 600000
