name: Deploy Development to Hostinger (Subdomain)

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build (development release)
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL_DEV }}
        run: npm run build

      - name: Ensure .htaccess is present in dist
        run: |
          if [ -f "public/.htaccess" ]; then
            cp -f public/.htaccess dist/.htaccess
          fi

      - name: Deploy via FTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR_DEV }}
          protocol: ftps
          dangerous-clean-slate: true
          log-level: minimal
          timeout: 600000
